# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Frontend Node

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Build Front
        run: |
          npm install
          npm run build
      - name: Copy project files
        run: Copy '${{ github.workspace }}/Play.Frontend/build//${{ github.workspace }}/Play.Frontend/build/**/*' '${{ github.workspace }}/publish'
      - name: Archive files
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ${{ github.workspace }}/publish/${{ github.run_id }}-WebApp.zip ${{ github.workspace }}/publish
      - name: Publish npm artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/publish/${{ github.run_id }}-WebApp.zip
          name: ${{ github.run_id }}-FrontWebApp                    